USE [W_GnBD]
ALTER INDEX ALL ON MNTGROUP
REBUILD;
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON MNTCATEGORY
REBUILD;
ALTER INDEX ALL ON MNTCATEGORY_TYPE
REBUILD;
ALTER INDEX ALL ON MNTGROUP_PSW
REBUILD;
ALTER INDEX ALL ON MNTMEMBER_PSW
REBUILD;
ALTER INDEX ALL ON MNTSOURCE
REBUILD;
ALTER INDEX ALL ON MNTMEMBER
REBUILD;
ALTER INDEX ALL ON MNTINCOME
REBUILD;
ALTER INDEX ALL ON MNTINVESTMENT
REBUILD;
ALTER INDEX ALL ON MNTEXPENSE
REBUILD;
GO