
--ASYNCPROCESS | Ver.: 2501
UPDATE [ASYNCPROCESS]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [ASYNCPROCESS]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--ASYNCPROCESSARGUMENT | Ver.: 2501
UPDATE [ASYNCPROCESSARGUMENT]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--ASYNCPROCESSATTACHMENTS | Ver.: 2501
UPDATE [ASYNCPROCESSATTACHMENTS]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--USERAUTHORIZATION | Ver.: 2501
UPDATE [USERAUTHORIZATION]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--MNTCATEGORY | Ver.: 2503
UPDATE [MNTCATEGORY]
SET [TYPE_ID] = NULL
where [TYPE_ID] in (0);
GO
--MNTGROUP_PSW | Ver.: 2508
UPDATE [MNTGROUP_PSW]
SET [GROUP_ID] = NULL
where [GROUP_ID] in (0);
UPDATE [MNTGROUP_PSW]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--MNTMEMBER_PSW | Ver.: 2508
UPDATE [MNTMEMBER_PSW]
SET [MEMBER_ID] = NULL
where [MEMBER_ID] in (0);
UPDATE [MNTMEMBER_PSW]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--MNTSOURCE | Ver.: 2509
UPDATE [MNTSOURCE]
SET [MEMBER_ID] = NULL
where [MEMBER_ID] in (0);
GO
--MNTMEMBER | Ver.: 2510
UPDATE [MNTMEMBER]
SET [GROUP_ID] = NULL
where [GROUP_ID] in (0);
GO
--MNTINCOME | Ver.: 2512
UPDATE [MNTINCOME]
SET [CATEGORY_ID] = NULL
where [CATEGORY_ID] in (0);
UPDATE [MNTINCOME]
SET [MEMBER_ID] = NULL
where [MEMBER_ID] in (0);
UPDATE [MNTINCOME]
SET [SOURCE_ID] = NULL
where [SOURCE_ID] in (0);
UPDATE [MNTINCOME]
SET [TYPE_ID] = NULL
where [TYPE_ID] in (0);
GO
--MNTINVESTMENT | Ver.: 2512
UPDATE [MNTINVESTMENT]
SET [CATEGORY_ID] = NULL
where [CATEGORY_ID] in (0);
UPDATE [MNTINVESTMENT]
SET [MEMBER_ID] = NULL
where [MEMBER_ID] in (0);
UPDATE [MNTINVESTMENT]
SET [SOURCE_ID] = NULL
where [SOURCE_ID] in (0);
UPDATE [MNTINVESTMENT]
SET [TYPE_ID] = NULL
where [TYPE_ID] in (0);
GO
--MNTEXPENSE | Ver.: 2513
UPDATE [MNTEXPENSE]
SET [CATEGORY_ID] = NULL
where [CATEGORY_ID] in (0);
UPDATE [MNTEXPENSE]
SET [MEMBER_ID] = NULL
where [MEMBER_ID] in (0);
UPDATE [MNTEXPENSE]
SET [SOURCE_ID] = NULL
where [SOURCE_ID] in (0);
UPDATE [MNTEXPENSE]
SET [TYPE_ID] = NULL
where [TYPE_ID] in (0);
UPDATE [MNTEXPENSE]
SET [GROUP_ID] = NULL
where [GROUP_ID] in (0);
GO


